name: ci

on:
  push:
    branches: [main, 'release/**', 'task/**', 'feature/**', 'epic/**']
    tags: ['**']
  pull_request:
    branches: [main, 'release/**', 'task/**', 'feature/**', 'epic/**']

jobs:

  test:
    name: Erlang ${{ matrix.otp_version }} build
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        otp_version: [28, 27, 26, 25]

    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: ${{ matrix.otp_version >= 26 && '3.25' || '3.22' }}
    - name: Check rebar3 Version
      run: rebar3 --version
    - name: Compile
      run: rebar3 compile
    - name: Format Checks
      run: rebar3 fmt --check
    - name: Xref Checks
      run: rebar3 xref
    - name: Dialyzer Checks
      run: rebar3 dialyzer
    - name: Run Tests
      run: rebar3 eunit -v
    - name: Test Coverage
      run: rebar3 as test cover -v --min_coverage=0
